CC		= arm-linux-gnueabi-g++-4.7
CFLAGS		= -g -c -Wall 
LDFLAGS		= 
SOURCES		= CLI.cpp tcpsocket/tcpstream.cpp tcpsocket/tcpacceptor.cpp
INCLUDES	= -I.
OBJECTS		= $(SOURCES:.cpp=.o)
TARGET		= CLI

all: $(SOURCES) $(TARGET)

$(TARGET): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) $< -o $@

clean:
	rm -rf $(OBJECTS) $(TARGET)

